name: CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/bank-nifty-trading:latest
    
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0
    
    - name: Terraform Init
      run: |
        cd infra
        terraform init
      env:
        DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
    
    - name: Terraform Apply
      run: |
        cd infra
        terraform apply -auto-approve
      env:
        DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
    
    - name: Get Droplet IP
      id: droplet-ip
      run: |
        cd infra
        echo "::set-output name=ip::$(terraform output -raw floating_ip)"
    
    - name: Deploy to Droplet
      uses: appleboy/ssh-action@master
      with:
        host: ${{ steps.droplet-ip.outputs.ip }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/bank-nifty-trading:latest
          docker-compose down
          docker-compose up -d
